apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    env: prod
    tier: frontend
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80