apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webpage
  name: aizawa
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    tier: frontend
  type: ClusterIP
status:
  loadBalancer: {}
