apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: prod
    tier: frontend
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  nodeSelector:
    env: prod
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    env: prod
    tier: backend
    app: redis
spec:
  containers:
  - name: redis
    image: redis
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  nodeSelector:
    env: prod
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    env: stage
    tier: frontend
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  nodeSelector:
    env: stage
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    env: stage
    tier: backend
    app: redis
spec:
  containers:
  - name: redis
    image: redis
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  nodeSelector:
    env: stage
---
