apiVersion: v1
kind: Pod
metadata:
  name: pod5
spec:
  containers:
    - name: pod5
      image:	 k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c" ]
      args:
        - echo '';
          echo hello $goosebumps 
      envFrom:
      - configMapRef:
          name: test5
  restartPolicy: Never
