apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hendrix
  name: hendrix
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: fedora
    name: hendrix
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
