apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mana
  name: mana
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: debian
    name: mana
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
