apiVersion: v1
kind: Pod
metadata:
  name: test2
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        memory: "270Mi"
        cpu: "268m"