apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  labels:
    name: myapp2
spec:
  containers:
  - name: test6
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Gi"
        cpu: "256g"
      requests:
        memory: "2560Mi"
        cpu: "5000m"      
    ports:
      - containerPort: 80
