apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c"]
      args:
        - echo '';
          echo whats up? This is the command ran inside the container;
          echo '';
          echo Bellow you will see the current variables in a pod && echo '';
          echo =================================== && echo '';
          env;
          echo '';
          echo =================================== && echo '';
          echo Now this is the variable we created in configmap being displayed;
          echo '';
          echo SPECIAL_LEVEL_KEY is $SPECIAL_LEVEL_KEY && echo '';
      env:
        # Define the environment variable
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: config1
              # Specify the key associated with the value
              key: mumei
  restartPolicy: Never