apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-4
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - prod
            - stage
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0