apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - prod
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: end
            operator: In
            values:
            - stage
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0