apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-5
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: asdfasdfa
            operator: In
            values:
            - asdfafa
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0