apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: queen
  labels:
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: queen
        image: alpine
        command:
          - "sleep"
          - "5000"