apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dafunk
  labels:
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: dafunk
        image: fedora
        command:
          - "sleep"
          - "5000"