apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-server-2
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: web-app
        image: nginx:1.16-alpine