apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: test5
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Gi"
        cpu: "256g"
      requests:
        memory: "2560Mi"
        cpu: "5000m"      
    ports:
      - containerPort: 80
