apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: test5
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
        cpu: "256m"
      limits:
        memory: "128Mi"
        cpu: "128m"      
    ports:
      - containerPort: 80
