apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-1
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 6
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: web-app
        image: nginx:1.16-alpine
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3 # if three checks fail in a row, then the pod is considered not ready
          successThreshold: 1 # if only one check passes, the pod is ready
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 15
