---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
# "namespace" omitted since ClusterRoles are not namespaced
  name: cluster-reader 
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-bind
subjects:
  - kind: User
    name: yeti # Name is case sensitive
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: miko # Name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: ClusterRole
    name: cluster-reader 
    apiGroup: rbac.authorization.k8s.io
---